---
cluster:
  name: k3s-monitoring

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway.lgtm.svc.cluster.local/loki/api/v1/push

clusterEvents:
  enabled: true
  collector: alloy-logs
  namespaces:
    - lgtm
    - traefik
    - authentik
    - cert-manager
    - pihole
    - kube-system
    - longhorn-system

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  labelsToKeep:
    [
      "app_kubernetes_io_name",
      "container",
      "instance",
      "job",
      "level",
      "namespace",
      "service_name",
      "service_namespace",
      "deployment_environment",
      "deployment_environment_name",
    ]
  structuredMetadata:
    pod: pod # Set structured metadata "pod" from label "pod"
  namespaces:
    - lgtm
    - traefik
    - authentik
    - cert-manager
    - pihole
    - kube-system
    - longhorn-system

# Collectors
alloy-singleton:
  enabled: false

alloy-metrics:
  enabled: false

alloy-logs:
  enabled: true
  # Required when using the Kubernetes API to pod logs
  alloy:
    mounts:
      varlog: false
      dockercontainers: false
    clustering:
      enabled: true

alloy-profiles:
  enabled: false

alloy-receiver:
  enabled: false
