site_name: Homelab
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    # - navigation.indexes
    # - navigation.sections
    # - navigation.tabs
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
nav:
  - Terminal:
    - Warp: terminal/warp/warp.md
    - Starship: terminal/starship/starship.md
  - k3s:
    - Pre-requisites:
      - Raspberry Pi: k3s/prerequisites/rpi.prereqs.md
    - SSH: k3s/ssh.md
    - Housekeeping: k3s/housekeeping.md
    - Install: k3s/k3sup.md
    - Kubevip: k3s/kubevip.md
    - Longhorn: k3s/longhorn.md
  - HTTPS:
    - cert-manager: traefik/cert_manager.md
    - Traefik: traefik/traefik.md