deployment:
  replicas: 3
service:
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.1.20"
# ingressRoute:
#   dashboard:
#     enabled: true
#     entryPoints: [web, websecure]
#     matchRule: Host(`dashboard.traefik.local.spaelling.xyz`)
#     tls:
#       secretName: traefik-dashboard-tls
#       domains:
#         - main: dashboard.traefik.local.spaelling.xyz
#     middlewares:
#       - name: authentik
#         namespace: authentik
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
ingressClass:
  name: traefik
  isDefaultClass: true
providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
    allowCrossNamespace: true
extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      annotations:
        kubernetes.io/ingress.class: traefik
      name: traefik-dashboard
      namespace: traefik
    spec:
      entryPoints:
        - web
        - websecure
      tls:
        secretName: traefik-dashboard-tls
        domains:
          - main: dashboard.traefik.local.spaelling.xyz
      routes:
        - kind: Rule
          match: "Host(`dashboard.traefik.local.spaelling.xyz`)"
          services:
            - kind: TraefikService
              name: api@internal
        # unable to get below to work
        #   middlewares:
        #     - name: authentik
        #       namespace: authentik
        #   priority: 10
        # - kind: Rule
        #   match: "Host(`dashboard.traefik.local.spaelling.xyz`) && PathPrefix(`/outpost.goauthentik.io/`)"
        #   priority: 15
        #   services:
        #     - kind: Service
        #       name: ak-outpost-authentik-embedded-outpost #ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
        #       namespace: authentik
        #       port: 9000
